CalinaITELEC1C/CalinaITELEC1C/Models/ErrorViewModel.cs
namespace CalinaITELEC1C.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CalinaITELEC1C/CalinaITELEC1C/Models/Instructor.cs
namespace CalinaITELEC1C.Models;
using CalinaITELEC1C.Models;
using Microsoft.AspNetCore.Mvc;

    public enum Rank
    {
        Instructor, AssistantProfessor, AssociateProfessor, Professor
    }
    public class Instructor
    {
        public int InstructorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsTenured { get; set; }
        public DateTime HiringDate { get; set; }
        public Rank InstructorRank { get; set; }

    }

CalinaITELEC1C/CalinaITELEC1C/Models/Student.cs
namespace CalinaITELEC1C.Models

{
    public enum Course
    {
        BSIT, BSCS, BSIS, OTHER
    }
    public class Student
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public double GPA { get; set; }
        public DateTime AdmissionDate { get; set; }
        public Course StudentCourse { get; set; }
        public string Email { get; set; }
    }
}

CalinaITELEC1C/CalinaITELEC1C/Controllers/HomeController.cs
using CalinaITELEC1C.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CalinaITELEC1C.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CalinaITELEC1C/CalinaITELEC1C/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using CalinaITELEC1C.Models;
using CalinaITELEC1C.Services;

namespace CalinaITELEC1C.Controllers
{
    public class InstructorController : Controller
    {
        private readonly IMyFakeDataService _dummyData;

        public InstructorController(IMyFakeDataService dummyData) //constructor
        {
            _dummyData = dummyData;
        }

            public IActionResult Index()
            {
                return View(_dummyData.InstructorsList);
            }
            public IActionResult ShowDetail(int id)
            {
                Instructor? instructor = _dummyData.InstructorsList.FirstOrDefault(st => st.InstructorId == id);

                if(instructor != null)
                    return View(instructor);
            
                return NotFound();
            }
            [HttpGet]
            public IActionResult AddInstructor()
            {
                return View();
            }
            [HttpPost]
            public IActionResult AddInstructor(Instructor newInstructor)
            {
                _dummyData.InstructorsList.Add(newInstructor);
                return RedirectToAction("Index");
        }
            [HttpGet]
            public IActionResult UpdateInstructor(int id)
            {
                Instructor? instructor = _dummyData.InstructorsList.FirstOrDefault(st => st.InstructorId == id);

                if (instructor != null)
                    return View(instructor);

                return NotFound();
            }
            [HttpPost]
            public IActionResult UpdateInstructor(Instructor InstructorChanges)
            {
                Instructor? instructor = _dummyData.InstructorsList.FirstOrDefault(st => st.InstructorId == InstructorChanges.InstructorId);
                if (instructor != null)
                {
                    instructor.FirstName = InstructorChanges.FirstName;
                    instructor.LastName = InstructorChanges.LastName;
                    instructor.InstructorRank = InstructorChanges.InstructorRank;
                    instructor.HiringDate = InstructorChanges.HiringDate;
                    instructor.IsTenured = InstructorChanges.IsTenured;
                }
                return RedirectToAction("Index");
        }

            [HttpGet]
            public IActionResult Delete(int id)
            {
                Instructor? instructor = _dummyData.InstructorsList.FirstOrDefault(st => st.InstructorId == id);

                if (instructor != null)
                    return View(instructor);

                return NotFound();
            }

            [HttpPost]
            public IActionResult Delete(Instructor InstructorDelete)
            {
                Instructor? instructor = _dummyData.InstructorsList.FirstOrDefault(st => st.InstructorId == InstructorDelete.InstructorId);
                if (instructor != null)
                    _dummyData.InstructorsList.Remove(instructor);

                return RedirectToAction("Index");
        }
    }
}

CalinaITELEC1C/CalinaITELEC1C/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using CalinaITELEC1C.Models;
using CalinaITELEC1C.Services;

namespace CalinaITELEC1C.Controllers
{
    public class StudentController : Controller
    {
        private readonly IMyFakeDataService _dummyData;

        public StudentController(IMyFakeDataService dummyData) //constructor
        {
            _dummyData = dummyData;
        }

        public IActionResult Index()
        {
            return View(_dummyData.StudentList);
        }
        public IActionResult ShowDetail(int id)
        {
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == id);

            if (student != null)
                return View(student);

            return NotFound();
        }
        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddStudent(Student newStudent)
        {
            _dummyData.StudentList.Add(newStudent);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult UpdateStudent(int id)
        {
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == id);

            if (student != null)
                return View(student);

            return NotFound();
        }
        [HttpPost]
        public IActionResult UpdateStudent(Student studentChanges)
        {
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == studentChanges.StudentId);
            if(student != null)
            {
                student.FirstName = studentChanges.FirstName;
                student.LastName = studentChanges.LastName;
                student.Email = studentChanges.Email;   
                student.StudentCourse = studentChanges.StudentCourse;
                student.AdmissionDate = studentChanges.AdmissionDate;
                student.GPA = studentChanges.GPA;
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == id);

            if (student != null)
                return View(student);

            return NotFound();
        }

        [HttpPost]
        public IActionResult Delete(Student newStudent)
        {
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == newStudent.StudentId);
            if (student != null)
                _dummyData.StudentList.Remove(student);

            return RedirectToAction("Index");
        }
    }
        /*
        public IActionResult Index()
        {
            Student st = new Student();
            st.StudentId = 1;
            st.StudentName = "Mark Calina";
            st.DateEnrolled = DateTime.Parse("25/08/2023");
            st.Email = "markgabriel.calina.cics@ust.edu.ph";

            ViewBag.Student = st.StudentId;
            ViewBag.StudentName = st.StudentName;
            ViewBag.StudentCourse = st.StudentCourse;
            ViewBag.Email = st.Email;
            ViewBag.DateEnrolled = st.DateEnrolled;
            return View();
        }
        */
    }

CalinaITELEC1C/CalinaITELEC1C/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CalinaITELEC1C/CalinaITELEC1C/Views/Instructor/AddInstructor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Instructor
<h1>Add Instructor</h1>
<form class='p-2 row gx-3 gy-2 align-items-center' method="POST" asp-action="AddInstructor" asp-controller="Instructor">
    <div class="form-group">
        <label asp-for="InstructorId">Instructor ID</label>
        <input class="form-control" asp-for="InstructorId" placeholder="Enter Instructor ID">
    </div>
    <div class="form-group">
        <label asp-for="FirstName">First Name</label>
        <input class="form-control" asp-for="FirstName" placeholder="Enter first name">
    </div>

    <div class="form-group">
        <label asp-for="LastName">Last Name</label>
        <input class="form-control" asp-for="LastName" placeholder="Enter last name">
    </div>
    <div class="form-group">
        <label asp-for="IsTenured">Status</label>
        <select class="form-control" asp-for="IsTenured">
            <option value="true">Full-Time</option>
            <option value="false">Part-Time</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="InstructorRank">Instructor Rank</label>
        <select class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Rank))" asp-for="InstructorRank">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="HiringDate">Date Hired</label>
        <input class="form-control" asp-for="HiringDate">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CalinaITELEC1C/CalinaITELEC1C/Views/Instructor/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Instructor;
<h1>Delete Instructor details?</h1>
<form class='p-2 row gx-3 gy-2 align-items-center' method="POST" asp-action="Delete" asp-controller="Instructor">
    <div class="form-group">
        <label asp-for="InstructorId" hidden>Instructor ID</label>
        <input class="form-control" asp-for="InstructorId" placeholder="Enter Instructor ID" hidden>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">First Name</label>
        <input class="form-control" asp-for="FirstName" placeholder="Enter first name" readonly>
    </div>

    <div class="form-group">
        <label asp-for="LastName">Last Name</label>
        <input class="form-control" asp-for="LastName" placeholder="Enter last name" readonly>
    </div>
    <div class="form-group">
        <label asp-for="IsTenured">Status</label>
        <select class="form-control" asp-for="IsTenured" readonly>
            <option value="true">Full-Time</option>
            <option value="false">Part-Time</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="InstructorRank">Instructor Rank</label>
        <select class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Rank))" asp-for="InstructorRank" readonly>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="HiringDate">Date Hired</label>
        <input class="form-control" asp-for="HiringDate" readonly>
    </div>
    <button type="submit" class="btn btn-danger">Delete</button>
    <button type="button" onclick="history.back()" class="btn btn-primary-secondary">Cancel</button>
</form>

CalinaITELEC1C/CalinaITELEC1C/Views/Instructor/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<Instructor>;
<h1>Instructor List</h1>
<input class="btn btn-primary" type="button" value="Add Instructor"
       onclick="@("window.location.href='" + @Url.Action("AddInstructor", "Instructor") + "'");" />
<table class="table table-dark">
    <tr>
        <th colspan="10">Instructor</th>
    </tr>
    <tr>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Rank</td>
        <td>Hiring Date</td>
        <td>Status</td>
        <td>ID</td>
        <td>Details</td>
        <td>Update</td>
        <td>Delete</td>
    </tr>
    @foreach (var instructor in Model)
    {
        <tr>
            <td>@instructor.FirstName</td>
            <td>@instructor.LastName</td>
            <td>@instructor.InstructorRank</td>
            <td>@instructor.HiringDate</td>
            <td>@{
                    if(instructor.IsTenured == true)
                    {
                        <span>Full-Time</span>
                    }
                    else
                    {
                        <span>Part-Time</span>
                    }
                }</td>
            <td>@instructor.InstructorId</td>
            <td><a class="btn btn-primary" asp-action="ShowDetail" asp-route-id="@instructor.InstructorId">Show Details</a></td>
            <td><a class="btn btn-info" asp-action="UpdateInstructor" asp-route-id="@instructor.InstructorId">Update</a></td>
            <td><a class="btn btn-danger" asp-action="Delete" asp-route-id="@instructor.InstructorId">Delete</a></td>

        </tr>
        
    }
</table>

CalinaITELEC1C/CalinaITELEC1C/Views/Instructor/ShowDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Instructor;
<h1>Instructor Details</h1>
<table class="table table-dark">
    <tr>
        <th>ID</th>
        <td>@Model.InstructorId</td>
    </tr>
    <tr>
        <th>Last Name</th>
        <td>@Model.LastName</td>
    </tr>
    <tr>
        <th>First Name</th>
        <td>@Model.FirstName</td>
    </tr>
    <tr>
        <th>Status</th>
        <td>@Model.IsTenured</td>
    </tr>
    <tr>
        <th>Hiring Date</th>
        <td>@Model.HiringDate</td>
    </tr>
    <tr>
        <th>Rank</th>
        <td>@Model.InstructorRank</td>
    </tr>
    

</table>

CalinaITELEC1C/CalinaITELEC1C/Views/Instructor/UpdateInstructor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Instructor;
<h1>Update Instructor</h1>
<form class='p-2 row gx-3 gy-2 align-items-center' method="POST" asp-action="UpdateInstructor" asp-controller="Instructor">
    <div class="form-group">
        <label asp-for="InstructorId" hidden>Instructor ID</label>
        <input class="form-control" asp-for="InstructorId" placeholder="Enter Instructor ID" hidden>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">First Name</label>
        <input class="form-control" asp-for="FirstName" placeholder="Enter first name">
    </div>

    <div class="form-group">
        <label asp-for="LastName">Last Name</label>
        <input class="form-control" asp-for="LastName" placeholder="Enter last name">
    </div>
    <div class="form-group">
        <label asp-for="IsTenured">Status</label>
        <select class="form-control" asp-for="IsTenured">
            <option value="true">Full-Time</option>
            <option value="false">Part-Time</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="InstructorRank">Instructor Rank</label>
        <select class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Rank))" asp-for="InstructorRank">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="HiringDate">Date Hired</label>
        <input class="form-control" asp-for="HiringDate">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" onclick="history.back()" class="btn btn-primary-secondary">Cancel</button>
</form>

CalinaITELEC1C/CalinaITELEC1C/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CalinaITELEC1C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CalinaITELEC1C.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CalinaITELEC1C</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CalinaITELEC1C - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CalinaITELEC1C/CalinaITELEC1C/Views/Student/AddStudent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Student;
<h1>Add Student</h1>
<form class='p-2 row gx-3 gy-2 align-items-center' method="POST" asp-action="AddStudent" asp-controller="Student">
    <div class="form-group">
        <label asp-for="StudentId">Student ID</label>
        <input class="form-control" asp-for="StudentId" placeholder="Enter Student ID">
    </div>
    <div class="form-group">
        <label asp-for="FirstName">Name</label>
        <input class="form-control" asp-for="FirstName" placeholder="Enter first name">
    </div>
    
    <div class="form-group">
        <label asp-for="LastName">Name</label>
        <input class="form-control" asp-for="LastName" placeholder="Enter last name">
    </div>
    <div class="form-group">
        <label asp-for="Email">Email address</label>
        <input class="form-control" asp-for="Email" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label asp-for="GPA">GPA</label>
        <input class="form-control" asp-for="GPA"  placeholder="Enter GPA">
    </div>
    <div class="form-group">
        <label asp-for="StudentCourse">Course</label>
        <select class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Course))" asp-for="StudentCourse"> 
        </select>
    </div>
    <div class="form-group">
        <label asp-for="AdmissionDate">Date Enrolled</label>
        <input class="form-control" asp-for="AdmissionDate">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CalinaITELEC1C/CalinaITELEC1C/Views/Student/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Student;
<h1>Delete Student Details?</h1>
<form class='p-2 row gx-3 gy-2 align-items-center' method="POST" asp-action="Delete" asp-controller="Student">
    <div class="form-group">
        <label asp-for="StudentId" hidden>Student ID</label>
        <input class="form-control" asp-for="StudentId" placeholder="Enter Student ID" hidden>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">Name</label>
        <input class="form-control" asp-for="FirstName" placeholder="Enter first name" readonly>
    </div>
    
    <div class="form-group">
        <label asp-for="LastName">Name</label>
        <input class="form-control" asp-for="LastName" placeholder="Enter last name" readonly>
    </div>
    <div class="form-group">
        <label asp-for="Email">Email address</label>
        <input class="form-control" asp-for="Email" aria-describedby="emailHelp" placeholder="Enter email" readonly>
    </div>
    <div class="form-group">
        <label asp-for="GPA">GPA</label>
        <input class="form-control" asp-for="GPA" placeholder="Enter GPA" readonly>
    </div>
    <div class="form-group">
        <label asp-for="StudentCourse">Course</label>
        <select class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Course))" asp-for="StudentCourse" readonly>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="AdmissionDate">Date Enrolled</label>
        <input class="form-control" asp-for="AdmissionDate" readonly>
    </div>
    <button type="submit" class="btn btn-danger">Delete</button>
    <button type="button" onclick="history.back()" class="btn btn-primary-secondary">Cancel</button>
</form>

CalinaITELEC1C/CalinaITELEC1C/Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<Student>;
<h1>Student List</h1>
<input class="btn btn-primary" type="button" value="Add Student"
       onclick="@("window.location.href='" + @Url.Action("addstudent", "Student") + "'");" />
<table class="table table-dark">
    <tr>
        <th colspan="10">Student</th>
    </tr>
    <tr>
        <td>First Name</td>
        <td>Last Name</td>
        <td>GPA</td>
        <td>Admission Date</td>
        <td>Student Course</td>
        <td>ID</td>
        <td>Email</td>
        <td>Details</td>
        <td>Update</td>
        <td>Delete</td>
    </tr>
    @foreach (var student in Model)
    {
        <tr>
            <td>@student.FirstName</td>
            <td>@student.LastName</td>
            <td>@student.GPA</td>
            <td>@student.AdmissionDate</td>
            <td>@student.StudentCourse</td>
            <td>@student.StudentId</td>
            <td>@student.Email</td>
            <td><a class="btn btn-primary"asp-action="ShowDetail" asp-route-id="@student.StudentId">Show Details</a></td>
            <td><a class="btn btn-info" asp-action="UpdateStudent" asp-route-id="@student.StudentId">Update</a></td>
            <td><a class="btn btn-danger" asp-action="Delete" asp-route-id="@student.StudentId">Delete</a></td>

        </tr>

    }
</table>
<!--

    <table>
        <tr>
            <th>Name:</th>
            <td>@ViewBag.StudentName</td>
        </tr>
        <tr>
            <th>Date Enrolled:</th>
            <td>@ViewBag.DateEnrolled</td>
        </tr>
        <tr>
            <th>StudentID:</th>
            <td>@ViewBag.StudentId</td>
        </tr>
        <tr>
            <th>Date Enrolled:</th>
            <td>@ViewBag.DateEnrolled</td>
        </tr>
    </table>

-->
    

CalinaITELEC1C/CalinaITELEC1C/Views/Student/ShowDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Student;
<h1>Student Details</h1>
<table class="table table-dark">
    <tr>
        <th>ID</th>
        <td>@Model.StudentId</td>
    </tr>
    <tr>
        <th>Last Name</th>
        <td>@Model.LastName</td>
    </tr>
    <tr>
        <th>First Name</th>
        <td>@Model.FirstName</td>
    </tr>
    <tr>
        <th>GPA</th>
        <td>@Model.GPA</td>
    </tr>
    <tr>
        <th>Admission Date</th>
        <td>@Model.AdmissionDate</td>
    </tr>
    <tr>
        <th>Student Course</th>
        <td>@Model.StudentCourse</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>@Model.Email</td>
    </tr>


</table>

CalinaITELEC1C/CalinaITELEC1C/Views/Student/UpdateStudent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Student;
<h1>Update Student</h1>
<form class='p-2 row gx-3 gy-2 align-items-center' method="POST" asp-action="UpdateStudent" asp-controller="Student">
    <div class="form-group">
        <label asp-for="StudentId" hidden>Student ID</label>
        <input class="form-control" asp-for="StudentId" placeholder="Enter Student ID" hidden>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">Name</label>
        <input class="form-control" asp-for="FirstName" placeholder="Enter first name">
    </div>
    
    <div class="form-group">
        <label asp-for="LastName">Name</label>
        <input class="form-control" asp-for="LastName" placeholder="Enter last name">
    </div>
    <div class="form-group">
        <label asp-for="Email">Email address</label>
        <input class="form-control" asp-for="Email" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label asp-for="GPA">GPA</label>
        <input class="form-control" asp-for="GPA" placeholder="Enter GPA">
    </div>
    <div class="form-group">
        <label asp-for="StudentCourse">Course</label>
        <select class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Course))" asp-for="StudentCourse">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="AdmissionDate">Date Enrolled</label>
        <input class="form-control" asp-for="AdmissionDate">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" onclick="history.back()" class="btn btn-primary-secondary">Cancel</button>
</form>